dist: trusty

language: node_js

node_js:
  - '8'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

sudo: required

before_install:
  - sudo apt-get -qq update
#  - curl -o- -L https://yarnpkg.com/install.sh | bash
#  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export NODE_ENV=development
#  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
#  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  directories:
    - node_modules

script:
  - npm run test-node
  - npm run lint
  - npm run test

env:
  - TRAVIS=travis CXX=g++-4.8
